### PR TITLE
Oak items, show progress on progress bar, fix initial shown value, show max level

### LINKED ISSUE #323: Oak Item progress bar shows infinity at max level
image

Instead of showing 1/Infinity, the bar should be blue with a text that says 'Maxed' in the middle.

### PR DESCRIPTION
**Pull request by RedSparr0w**
Closes #323 

- [x] Show progress amount in the progress bar instead of tooltip:

Before | After
:--: | :--:
Screenshot from 2019-06-06 13-29-36 | Screenshot from 2019-06-06 13-29-00

- [x] Fix the oak item shown on initial load:

Before | After
:--: | :--:
Screenshot from 2019-06-06 13-28-07 | Screenshot from 2019-06-06 13-25-57

- [x] Show when the player has reached the maximum level [#323]:

Before | After
:--: | :--:
Screenshot from 2019-06-06 13-30-23 | Screenshot from 2019-06-06 13-30-09

### CODE REVIEW

File: src/scripts/oakitems/OakItem.ts [hunk 1]
```diff
@@ -31,7 +31,7 @@ class OakItem {
         if (OakItemRunner.selectedItem().canUpgrade()) {
             return "Cost: " + GameConstants.OAKITEM_MONEY_COST[OakItemRunner.selectedItem().level()];
         }
-        return OakItemRunner.selectedItem().getNormalizedPlayerExp() + "/" + OakItemRunner.selectedItem().getNormalizedRequiredExp();
+        return OakItemRunner.inspectedItem().getNormalizedPlayerExp() + "/" + OakItemRunner.inspectedItem().getNormalizedRequiredExp();
```
Comment (RedSparr0w) [inline src/scripts/oakitems/OakItem.ts]: This line gave me so much trouble, I couldn't figure out why it wasn't updating the value to the item that was being hovered over.. didn't expect it to be using `selectedItem` as nothing else was :laughing:

File: src/index.html [hunk 2]
```diff
@@ -535,16 +535,16 @@ <h1>Pokéclicker</h1>
...
-                                        'oak-item-locked': !OakItemRunner.isUnlocked($data.id)
-
-                                        },
-                                 event: {
+                                  css: {
+                                    'oak-item-small-selected': OakItemRunner.isActive($data.id),
+                                    'oak-item-small': !OakItemRunner.isActive($data.id),
+                                    'oak-item-locked': !OakItemRunner.isUnlocked($data.id)
+                                  },
+                                  event: {
```
Comment (RedSparr0w) [inline src/index.html]: Nothing has actually changed here, I've just tidied it slightly.
